# vim:ft=ansible:
---
- name: Try mount
  hosts: all
  gather_facts: false
  ignore_errors: true

  tasks:
    - name: Mounting NFS volume to localhost
      become: true
      ansible.posix.mount:
        src: "{{ src_path }}"
        path: "{{ local_path }}"
        state: mounted
        fstype: nfs
        opts: rw,sync,hard

    - name: Create a voulme mount
      containers.podman.podman_container:
        name: nfs-enabled-elite-app
        image: elite-app:latest
        state: started
        mounts:
          - type=bind,source=/nfsfileshare,destination=/nfsfileshare
